
import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { factory, score, answers, failed_ids, tips } = body;

    const GEMINI_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_KEY) throw new Error('Missing GEMINI_API_KEY');

    const scoreBand =
      score >= 90 ? 'DPP COMPLIANT' :
      score >= 70 ? 'CONDITIONALLY COMPLIANT' :
      score >= 50 ? 'DEVELOPING' : 'NON-COMPLIANT';

    const prompt = `
You are an expert EU ESPR Textile Compliance Advisor.
Analyze this factory's DPP self-assessment and generate a structured JSON report.

FACTORY DETAILS:
- Name: ${factory.factory_name || 'Unknown Factory'}
- Country: ${factory.country || 'Bangladesh'}
- Supply Chain Tier: ${factory.tier_level || 'Tier 1'}
- Overall Score: ${score}/100
- Compliance Band: ${scoreBand}
- Factory Type: ${factory.factory_type || 'RMG/Garment'}

ASSESSMENT ANSWERS (question id: answer value):
${JSON.stringify(answers, null, 2)}

FAILED QUESTIONS (scored 0 points):
${JSON.stringify(failed_ids || [], null, 2)}

RULES:
- Be specific, technical, and actionable
- Reference exact ISO/REACH/ESPR standards
- For Bangladesh factories, reference BGMEA where relevant
- Keep executive summary to 2-3 sentences
- List maximum 5 critical actions, sorted by priority
- Include realistic timelines (weeks/months)

Respond ONLY with this exact JSON structure, no markdown:
{
  "executive_summary": "2-3 sentence professional overview of the factory compliance status",
  "compliance_band_explanation": "What this score means for EU market access",
  "strengths": ["strength 1", "strength 2", "strength 3"],
  "critical_actions": [
    {
      "priority": 1,
      "category": "Category name",
      "issue": "What failed or is missing",
      "fix_action": "Exactly what to do, step by step",
      "timeline": "e.g. 2-4 weeks",
      "regulatory_reference": "e.g. ISO 3759:2011 or REACH Art. 33"
    }
  ],
  "buyer_ready_statement": "One professional sentence a factory can show EU buyers",
  "next_assessment_date": "Recommended reassessment timeframe",
  "disclaimer": "This report is generated by an AI system based on self-reported data. It is an advisory tool and does not constitute legal certification. Independent lab testing and official certification bodies must be consulted for legally binding compliance."
}
`;

    const geminiRes = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.3, maxOutputTokens: 1500 }
        })
      }
    );

    if (!geminiRes.ok) throw new Error('Gemini API error: ' + geminiRes.status);

    const geminiData = await geminiRes.json();
    const rawText = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text || '';
    const cleaned = rawText.replace(/```json/g,'').replace(/```/g,'').trim();
    const aiReport = JSON.parse(cleaned);

    return NextResponse.json({ success: true, report: aiReport });

  } catch (err: any) {
    console.error('Gemini error:', err.message);
    // FALLBACK: rule-based report if Gemini fails
    const fallback = generateFallbackReport(err);
    return NextResponse.json({ success: true, report: fallback, fallback: true });
  }
}

function generateFallbackReport(err: any) {
  return {
    executive_summary: "Your factory has completed the DPP compliance assessment. Based on your self-reported data, we have identified key areas requiring attention to meet EU ESPR 2027 requirements. Please review the critical actions below and prioritize implementation.",
    compliance_band_explanation: "Your current score indicates areas where immediate action is needed to achieve EU Digital Product Passport compliance before the 2027 mandate deadline.",
    strengths: [
      "Factory has engaged in the DPP compliance process",
      "Assessment data has been recorded for tracking progress",
      "Improvement roadmap is now available for implementation"
    ],
    critical_actions: [
      {
        priority: 1,
        category: "Factory Identity",
        issue: "GS1 Global Location Number may not be registered",
        fix_action: "Register at gs1.org/services/gln for a free GLN number. This is mandatory for EU DPP traceability.",
        timeline: "1-2 weeks",
        regulatory_reference: "EU ESPR Regulation Article 9 — Traceability"
      },
      {
        priority: 2,
        category: "Chemical Compliance",
        issue: "REACH compliance audit documentation needed",
        fix_action: "Commission a REACH audit from an EU-approved laboratory. Contact SGS, Bureau Veritas, or Intertek in Bangladesh.",
        timeline: "4-6 weeks",
        regulatory_reference: "REACH Regulation (EC) No 1907/2006 Article 33"
      },
      {
        priority: 3,
        category: "Physical Testing",
        issue: "ISO test certifications may be missing or expired",
        fix_action: "Submit fabric samples to a BGMEA-approved lab for ISO 3759 shrinkage and ISO 16322-3 spirality testing.",
        timeline: "3-4 weeks",
        regulatory_reference: "ISO 3759:2011 and ISO 16322-3"
      }
    ],
    buyer_ready_statement: "This factory has initiated EU ESPR DPP compliance assessment and is actively implementing improvements to meet the 2027 mandate.",
    next_assessment_date: "Reassess in 3 months after implementing critical actions",
    disclaimer: "This report is generated by an AI system based on self-reported data. It is an advisory tool and does not constitute legal certification. Independent lab testing and official certification bodies must be consulted for legally binding compliance."
  };
}
